### ISSUE TITLE
[Bug]: FileSystem cant not use -O1 or higher

### ISSUE THREAD

**Issue by adonzheng** [ARM-software/MDK-Middleware#70] opened 2024-10-24 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a project that uses FileSystem to drive the SD card. When I tested it, I found a serious problem. When I optimized it using -O0, it worked fine. When using other values, it frequently failed to Mount (fsStatus = fsMediaError).

### Affected components

- [X] Filesystem
- [ ] Network
- [ ] USB_Device
- [ ] USB_Host

### Version

Middleware last version.
STM32CubeMX last version.
MCU: STM32F407VE
SDIO-4bit mode.
PD14 as sdcard insert check pin .

### Blocker

- [ ] blocker

**Comment by VladimirUmek** [comment] 2024-10-24 10:33
Hi,
does your project use MCI driver from the[ CMSIS-Driver_STM32 pack](https://github.com/Open-CMSIS-Pack/CMSIS-Driver_STM32/releases/tag/v1.0.0)? If so, I suggest that you update the MCI driver by either [building](https://github.com/Open-CMSIS-Pack/CMSIS-Driver_STM32?tab=readme-ov-file#generate-software-pack) CMSIS-Driver_STM32 pack (development version) or comparing/merging MCI driver source code [from the repository](https://github.com/Open-CMSIS-Pack/CMSIS-Driver_STM32).

In the released version of the CMSIS-Driver_STM32 pack there is a bug in MCI driver [related to handling of the CLKCR register](https://github.com/Open-CMSIS-Pack/CMSIS-Driver_STM32/commit/1515a7cf1551fc63871eefabac2f58b93b0d6e71) which has been fixed and is scheduled for the next release. The behavior you described is likely to be caused by this bug.

**Comment by adonzheng** [comment] 2024-10-25 02:00
I downloaded the latest CMSIS-Driver_STM32 and put it into my project. I tested it for around 10 hours with MDK and GNU. There were no errors found in -O3 mode.

**Comment by jkrech** [comment] 2024-10-25 05:55
Fixed in CMSIS-Driver_STM32 - see https://github.com/Open-CMSIS-Pack/CMSIS-Driver_STM32/pull/12
Will be included in the next release of ARM::CMSIS-Driver_STM32 version **> 1.0.0**

**Closed by jkrech** 2024-10-25 05:55 UTC
Labels: bug
